apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-prepper
  labels:
    app: data-prepper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-prepper
  template:
    metadata:
      labels:
        app: data-prepper
    spec:
      containers:
        - name: data-prepper
          image: opensearchproject/data-prepper:latest
          env:
            - name: OPENSEARCH_ENDPOINT
              value: "http://opensearch:9200"
          ports:
            - containerPort: 21893
          volumeMounts:
            - name: data-prepper-pipelines
              mountPath: /usr/share/data-prepper/pipelines/pipelines.yaml
              subPath: data-prepper-pipelines.yaml
            - name: data-prepper-config
              mountPath: /usr/share/data-prepper/config/data-prepper-config.yaml
              subPath: data-prepper-config.yaml
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: data-prepper-pipelines
          configMap:
            name: data-prepper-pipelines
        - name: data-prepper-config
          configMap:
            name: data-prepper-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-prepper-pipelines
data:
  data-prepper-pipelines.yaml: |
    version: 2

    otel-telemetry:
      source:
        otlp:
          output_format: opensearch
          ssl: false
      route:
        - logs: 'getEventType() == "LOG"'
        - metrics: 'getEventType() == "METRIC"'
        - traces: 'getEventType() == "TRACE"'
      sink:
        - opensearch:
            routes:
              - logs
            hosts: ["http://opensearch:9200"]
            index: ss4o_logs-%{yyyy.MM.dd}
            insecure: true
        - pipeline:
            name: otel-metrics
            routes:
              - metrics
        - pipeline:
            name: otel-traces
            routes:
              - traces

    otel-metrics:
      source:
        pipeline:
          name: otel-telemetry
      processor:
        - otel_metrics:
      sink:
        - opensearch:
            hosts: ["http://opensearch:9200"]
            index: ss4o_metrics-otel-%{yyyy.MM.dd}
            index_type: custom
            insecure: true

    otel-traces:
      source:
        pipeline:
          name: otel-telemetry
      processor:
        - otel_trace_raw:
      sink:
        - opensearch:
            hosts: ["http://opensearch:9200"]
            index_type: trace-analytics-raw
            insecure: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-prepper-config
data:
  data-prepper-config.yaml: |
    ssl: false
    peer_forwarder:
      ssl: false
---
apiVersion: v1
kind: Service
metadata:
  name: data-prepper
spec:
  selector:
    app: data-prepper
  ports:
    - port: 21893
      targetPort: 21893
