apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - expenses-deployment.yaml
  - gateway-deployment.yaml
  - notifications-deployment.yaml
  - rabbitmq-deployment.yaml
  - redis-deployment.yaml
  - sqlserver-deployment.yaml
labels:
  - includeSelectors: true
    pairs:
      app: microservices-app
      managed-by: kustomize
