apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_CLIENT_ID_EXPENSES: "expenses-app"
  APP_CLIENT_ID_GATEWAY: "gateway-app"
  APP_DATABASE_EXPENSES: "expenses"
  APP_USERNAME: "mezdelex"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-env
data:
  APP_DATA_PROTECTION_KEY_PATH: "/app/keys"
  ASPNETCORE_HTTPS_PORTS: "8100"
  ASPNETCORE_HTTP_PORTS: "8000"
  AUDIENCES: "expenses-app"
  CLIENT_ID: "gateway-app"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: expenses-env
data:
  APP_DATA_PROTECTION_KEY_PATH: "/app/keys"
  ASPNETCORE_HTTPS_PORTS: "8101"
  ASPNETCORE_HTTP_PORTS: "8001"
  CLIENT_ID: "expenses-app"
  DATABASE: "expenses"
  ISSUER: "gateway-app"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-env
data:
  ASPNETCORE_HTTPS_PORTS: "8102"
  ASPNETCORE_HTTP_PORTS: "8002"
