apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_USERNAME: "mezdelex"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-env
data:
  APP_DATA_PROTECTION_KEY_PATH: "/app/keys"
  ASPNETCORE_URLS: "http://+:8000;https://+:8100"
  AUDIENCES: "expenses-app"
  CLIENT_ID: "gateway-app"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: expenses-env
data:
  APP_DATA_PROTECTION_KEY_PATH: "/app/keys"
  ASPNETCORE_URLS: "http://+:8001;https://+:8101"
  CLIENT_ID: "expenses-app"
  DATABASE: "expenses"
  ISSUER: "gateway-app"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-env
data:
  ASPNETCORE_URLS: "http://+:8002;https://+:8102"
