apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  APP_PASSWORD: TGFwR01oWm41NWRlb21HMmpsTFo=
  APP_CLIENT_SECRET: cm9mbGNvcHRlcnJvZmxjb3B0ZXJyb2ZsY29wdGVycm9mbGNvcHRlcnJvZmxjb3B0ZXI=
