global using System.Linq.Expressions;
global using Application.Abstractions;
global using Application.Features.Commands;
global using static Application.Features.Commands.DeleteCategoryCommand;
global using static Application.Features.Commands.DeleteExpenseCommand;
global using static Application.Features.Commands.PatchCategoryCommand;
global using static Application.Features.Commands.PatchExpenseCommand;
global using static Application.Features.Commands.PostCategoryCommand;
global using static Application.Features.Commands.PostExpenseCommand;
global using Application.Features.DomainEvents;
global using Application.Features.Queries;
global using static Application.Features.Queries.GetCategoriesQuery;
global using static Application.Features.Queries.GetCategoryQuery;
global using static Application.Features.Queries.GetExpenseQuery;
global using static Application.Features.Queries.GetPaginatedCategoriesQuery;
global using static Application.Features.Queries.GetPaginatedExpensesQuery;
global using Application.Features.Shared;
global using Application.Profiles;
global using Application.Repositories;
global using AutoFixture;
global using AutoMapper;
global using Domain.Cache;
global using Domain.Entities;
global using static Domain.Extensions.Collections;
global using Domain.Identity;
global using Domain.Persistence;
global using Domain.Specifications;
global using FluentAssertions;
global using FluentValidation;
global using FluentValidation.Results;
global using Microsoft.AspNetCore.Http;
global using Microsoft.EntityFrameworkCore.Query;
global using Microsoft.Extensions.Logging;
global using MockQueryable;
global using Moq;
global using UnitTests.Mocks;
