global using System.IO.Hashing;
global using System.Text;
global using System.Text.Json;
global using Application.Abstractions;
global using Application.Contexts;
global using static Application.Features.DomainEvents.PatchedCategoryEvent;
global using static Application.Features.DomainEvents.PatchedExpenseEvent;
global using static Application.Features.DomainEvents.PostedCategoryEvent;
global using static Application.Features.DomainEvents.PostedExpenseEvent;
global using Application.Repositories;
global using Application.Responses;
global using Ardalis.Specification;
global using Ardalis.Specification.EntityFrameworkCore;
global using Domain.Cache;
global using Domain.Constants;
global using Domain.Entities;
global using Domain.Enums;
global using Domain.Identity;
global using Domain.Persistence;
global using Infrastructure.Cache;
global using Infrastructure.Contexts;
global using Infrastructure.Extensions;
global using Infrastructure.Interceptors;
global using Infrastructure.MessageBrokers.RabbitMQ;
global using Infrastructure.Persistence;
global using Infrastructure.Repositories;
global using MassTransit;
global using MassTransit.Logging;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.DataProtection;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.IdentityModel.Tokens;
global using OpenTelemetry.Exporter;
global using OpenTelemetry.Metrics;
global using OpenTelemetry.Resources;
global using OpenTelemetry.Trace;
global using StackExchange.Redis;
